config/routes.rb
Rails.application.routes.draw do
  resources :sales

  resources :customers

  resources :employees

  resources :quotes

  resources :cars

  resources :sales_statuses

  resources :quote_statuses

  resources :emp_positions

  resources :colors

  resources :years

  resources :makes

  root 'sales#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :quotes
  belongs_to :color
  belongs_to :make
  belongs_to :year

  def getModel
    "#{make.make_name}"
  end
end

app/models/color.rb
class Color < ActiveRecord::Base
  has_many :cars
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :sales
end

app/models/emp_position.rb
class EmpPosition < ActiveRecord::Base
  has_many :employees
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :emp_position
  has_many :sales
end

app/models/make.rb
class Make < ActiveRecord::Base
  has_many :cars
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :quote_status
  has_many :sales
  belongs_to :car
end

app/models/quote_status.rb
class QuoteStatus < ActiveRecord::Base
  has_many :quotes
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :quote
  belongs_to :sales_status
  belongs_to :employee
  belongs_to :customer
end

app/models/sales_status.rb
class SalesStatus < ActiveRecord::Base
  has_many :sales
end

app/models/year.rb
class Year < ActiveRecord::Base
  has_many :cars
end

app/controllers/sales_statuses_controller.rb
class SalesStatusesController < ApplicationController
  before_action :set_sales_status, only: [:show, :edit, :update, :destroy]

  # GET /sales_statuses
  # GET /sales_statuses.json
  def index
    @sales_statuses = SalesStatus.all
  end

  # GET /sales_statuses/1
  # GET /sales_statuses/1.json
  def show
  end

  # GET /sales_statuses/new
  def new
    @sales_status = SalesStatus.new
  end

  # GET /sales_statuses/1/edit
  def edit
  end

  # POST /sales_statuses
  # POST /sales_statuses.json
  def create
    @sales_status = SalesStatus.new(sales_status_params)

    respond_to do |format|
      if @sales_status.save
        format.html { redirect_to @sales_status, notice: 'Sales status was successfully created.' }
        format.json { render :show, status: :created, location: @sales_status }
      else
        format.html { render :new }
        format.json { render json: @sales_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales_statuses/1
  # PATCH/PUT /sales_statuses/1.json
  def update
    respond_to do |format|
      if @sales_status.update(sales_status_params)
        format.html { redirect_to @sales_status, notice: 'Sales status was successfully updated.' }
        format.json { render :show, status: :ok, location: @sales_status }
      else
        format.html { render :edit }
        format.json { render json: @sales_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales_statuses/1
  # DELETE /sales_statuses/1.json
  def destroy
    @sales_status.destroy
    respond_to do |format|
      format.html { redirect_to sales_statuses_url, notice: 'Sales status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sales_status
      @sales_status = SalesStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sales_status_params
      params.require(:sales_status).permit(:status_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sales_statuses_helper.rb
module SalesStatusesHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/sales_statuses/_form.html.erb
<%= form_for(@sales_status) do |f| %>
  <% if @sales_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sales_status.errors.count, "error") %> prohibited this sales_status from being saved:</h2>

      <ul>
      <% @sales_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status_type %><br>
    <%= f.text_field :status_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales_statuses/edit.html.erb
<h1>Editing Sales Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @sales_status %> |
<%= link_to 'Back', sales_statuses_path %>

app/views/sales_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Status type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales_statuses.each do |sales_status| %>
      <tr>
        <td><%= sales_status.status_type %></td>
        <td><%= link_to 'Show', sales_status %></td>
        <td><%= link_to 'Edit', edit_sales_status_path(sales_status) %></td>
        <td><%= link_to 'Destroy', sales_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sales status', new_sales_status_path %>

app/views/sales_statuses/new.html.erb
<h1>New Sales Status</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_statuses_path %>

app/views/sales_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status type:</strong>
  <%= @sales_status.status_type %>
</p>

<%= link_to 'Edit', edit_sales_status_path(@sales_status) %> |
<%= link_to 'Back', sales_statuses_path %>