config/routes.rb
Rails.application.routes.draw do
  resources :sales

  resources :customers

  resources :employees

  resources :quotes

  resources :cars

  resources :sales_statuses

  resources :quote_statuses

  resources :emp_positions

  resources :colors

  resources :years

  resources :makes

  root 'sales#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :quotes
  belongs_to :color
  belongs_to :make
  belongs_to :year

  def getModel
    "#{make.make_name}"
  end
end

app/models/color.rb
class Color < ActiveRecord::Base
  has_many :cars
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :sales
end

app/models/emp_position.rb
class EmpPosition < ActiveRecord::Base
  has_many :employees
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :emp_position
  has_many :sales
end

app/models/make.rb
class Make < ActiveRecord::Base
  has_many :cars
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :quote_status
  has_many :sales
  belongs_to :car
end

app/models/quote_status.rb
class QuoteStatus < ActiveRecord::Base
  has_many :quotes
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :quote
  belongs_to :sales_status
  belongs_to :employee
  belongs_to :customer
end

app/models/sales_status.rb
class SalesStatus < ActiveRecord::Base
  has_many :sales
end

app/models/year.rb
class Year < ActiveRecord::Base
  has_many :cars
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:make_id, :year_id, :color_id, :vin, :price)
    end
end

app/controllers/makes_controller.rb
class MakesController < ApplicationController
  before_action :set_make, only: [:show, :edit, :update, :destroy]

  # GET /makes
  # GET /makes.json
  def index
    @makes = Make.all
  end

  # GET /makes/1
  # GET /makes/1.json
  def show
  end

  # GET /makes/new
  def new
    @make = Make.new
  end

  # GET /makes/1/edit
  def edit
  end

  # POST /makes
  # POST /makes.json
  def create
    @make = Make.new(make_params)

    respond_to do |format|
      if @make.save
        format.html { redirect_to @make, notice: 'Make was successfully created.' }
        format.json { render :show, status: :created, location: @make }
      else
        format.html { render :new }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /makes/1
  # PATCH/PUT /makes/1.json
  def update
    respond_to do |format|
      if @make.update(make_params)
        format.html { redirect_to @make, notice: 'Make was successfully updated.' }
        format.json { render :show, status: :ok, location: @make }
      else
        format.html { render :edit }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /makes/1
  # DELETE /makes/1.json
  def destroy
    @make.destroy
    respond_to do |format|
      format.html { redirect_to makes_url, notice: 'Make was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_make
      @make = Make.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def make_params
      params.require(:make).permit(:make_name)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:quote_id, :customer_id, :employee_id, :sale_status_id, :date, :total)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make_id %><br>
    <%= f.collection_select :make_id, Make.all, :id, :make_name %>
  </div>
  <div class="field">
    <%= f.label :year_id %><br>
    <%= f.collection_select :year_id, Year.all, :id, :year_date %>
  </div>
  <div class="field">
    <%= f.label :color_id %><br>
    <%= f.collection_select :color_id, Color.all, :id , :color_name %>
  </div>
  <div class="field">
    <%= f.label :vin %><br>
    <%= f.text_field :vin %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cars</h1>

<table>
  <thead>
    <tr>
      <th>Make</th>
      <th>Year</th>
      <th>Color</th>
      <th>Vin</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.make.make_name %></td>
        <td><%= car.year.year_date %></td>
        <td><%= car.color.color_name %></td>
        <td><%= car.vin %></td>
        <td><%= car.price %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @car.make.make_name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year.year_date %>
</p>

<p>
  <strong>Color:</strong>
  <%= @car.color.color_name %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @car.vin %>
</p>

<p>
  <strong>Price:</strong>
  <%= @car.price %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/makes/_form.html.erb
<%= form_for(@make) do |f| %>
  <% if @make.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@make.errors.count, "error") %> prohibited this make from being saved:</h2>

      <ul>
      <% @make.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make_name %><br>
    <%= f.text_field :make_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/makes/edit.html.erb
<h1>Editing Make</h1>

<%= render 'form' %>

<%= link_to 'Show', @make %> |
<%= link_to 'Back', makes_path %>

app/views/makes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Makes</h1>

<table>
  <thead>
    <tr>
      <th>Make name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @makes.each do |make| %>
      <tr>
        <td><%= make.make_name %></td>
        <td><%= link_to 'Show', make %></td>
        <td><%= link_to 'Edit', edit_make_path(make) %></td>
        <td><%= link_to 'Destroy', make, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Make', new_make_path %>

app/views/makes/new.html.erb
<h1>New Make</h1>

<%= render 'form' %>

<%= link_to 'Back', makes_path %>

app/views/makes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make name:</strong>
  <%= @make.make_name %>
</p>

<%= link_to 'Edit', edit_make_path(@make) %> |
<%= link_to 'Back', makes_path %>

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote_id %><br>
    <%= f.collection_select :quote_id, Quote.all, :id, :id %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.collection_select :customer_id, Customer.all, :id , :name %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.collection_select :employee_id, Employee.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :sale_status_id %><br>
    <%= f.collection_select :sale_status_id, SalesStatus.all, :id, :status_type %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.text_field :total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>

<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th>Customer</th>
      <th>Employee</th>
      <th>Sale status</th>
      <th>Date</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.quote.quote_id %></td>
        <td><%= sale.customer.name %></td>
        <td><%= sale.employee.name %></td>
        <td><%= sale.sales_status.status_type %></td>
        <td><%= sale.date %></td>
        <td><%= sale.total %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @sale.quote.quote_id %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @sale.customer.name %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @sale.employee.name %>
</p>

<p>
  <strong>Sale status:</strong>
  <%= @sale.sales_status.status_type %>
</p>

<p>
  <strong>Date:</strong>
  <%= @sale.date %>
</p>

<p>
  <strong>Total:</strong>
  <%= @sale.total %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>